version: 2.1
jobs:
  hello-world:
    docker:  
    - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Hello World"
          command: "echo Hello, World!"

workflows:
  say-hello-world: 
    jobs:
      - hello-world
